export const dayMap = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thrusday",
  "Friday",
  "Saturday",
  "Sunday",
];

export const monthMap = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export const conditionMap = {
  clear: ["Sunny"],
  "cloud-at-night": [],
  cloudy: ["Partly cloudy", "Cloudy", "Overcast"],
  mist: ["Mist", "Fog", "Freezing fog"],
  night: ["Clear"],
  rain: [
    "Patchy rain possible",
    "Patchy freezing drizzle possible",
    "Thundery outbreaks possible",
    "Patchy light drizzle",
    "Light drizzle",
    "Freezing drizzle",
    "Heavy freezing drizzle",
    "Patchy light rain",
    "Light rain",
    "Moderate rain at times",
    "Moderate rain",
    "Heavy rain at times",
    "Heavy rain",
    "Light freezing rain",
    "Moderate or heavy freezing rain",
    "Light rain shower",
    "Moderate or heavy rain shower",
  ],
  snow: [
    "Patchy snow possible",
    "Patchy sleet possible",
    "Blowing snow",
    "Blizzard",
    "Light sleet",
    "Moderate or heavy sleet",
    "Patchy light snow",
    "Light snow",
    "Patchy moderate snow",
    "Moderate snow",
    "Patchy heavy snow",
    "Heavy snow",
    "Ice pellets",
    "Light sleet showers",
    "Moderate or heavy sleet showers",
    "Light snow showers",
    "Moderate or heavy snow showers",
    "Light showers of ice pellets",
    "Moderate or heavy showers of ice pellets",
  ],
  thunderstorm: [
    "Torrential rain shower",
    "Patchy light rain with thunder",
    "Moderate or heavy rain with thunder",
    "Patchy light snow with thunder",
    "Moderate or heavy snow with thunder",
  ],
};
